name: Function App Deploy

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
        default: "3.10"
        description: "Specifies the python version"
      dir:
        required: true
        type: string
        description: "Specifies the directory of the Azure Function"
      function_name: 
        required: true
        type: string
        description: "Specifies the name of the Azure Function"
    secrets:
      AZURE_TENANT_ID:
        required: true
        description: "Specifies the tenant id."
      AZURE_CLIENT_ID:
        required: true
        description: "Specifies the client id."
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: "Specifies the subscription id."

jobs:
  deployment:
    name: Function App Deploy
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Check out the repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ inputs.python_version }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.python_version }}'

      - name: 'Resolve Project Dependencies Using Pip'
        id: python_dependancies
        shell: bash
        run: |
          pushd '${{ inputs.function_directory }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: deploy_function
        with:
          app-name: ${{ inputs.function_name }}
          package: ${{ inputs.dir }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true