name: Hello World!

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, '${{ inputs.name }}'!